[pools."限定棋盘"]
# 限定棋盘由几乎不会变动的常驻部分和需要随版本更新的限定部分组成
# 每期的限定内容有四个：角色本体、时装（皮肤）、改装件（痛车涂装）、滑翔翼
items = [
    # A 级角色
    "角色·哈尼娅",
    "角色·翳",
    "角色·海月",
    "角色·薄荷",
    "角色·埃德嘉",
    "角色·阿德勒",
    # A 级弧盘
    "弧盘·被遗忘者",
    "弧盘·开始净空",
    "弧盘·当心头顶",
    "弧盘·勿忘伞",
    "弧盘·拔刀",
    # B 级弧盘
    "弧盘·成功的第一步",
    "弧盘·「电音」狂欢",
    "弧盘·危险游戏",
    "弧盘·笑口常开",
    "弧盘·「我们。」",
    # 道具
    "道具·质实骰子", # 用于限定棋盘的抽卡道具
    "道具·失纬棋子",
    "道具·迷迭棋子",

    # 以下内容需要随版本更新
    # 1.0 王牌一代目 https://www.bilibili.com/opus/1193982012627615752
    "角色·娜娜莉",
    "时装·华丽飞踢",
    "改装件·萌虎来袭-涂装",
    "滑翔翼·副手的副手",
    # 1.0 独酌胧月流 https://www.bilibili.com/opus/1199161743184494629
    "角色·浔",
    "时装·兰花不菲",
    "改装件·秋色残影-涂装",
    "滑翔翼·幽兰",
    # 1.1 久梦初醒时 https://www.bilibili.com/opus/1206598908525936646
    "角色·安魂曲",
    "时装·鎏金交响诗",
    "改装件·番茄酱巡航-涂装",
    "滑翔翼·好柿成双",
    # 1.1 无归路 https://www.bilibili.com/opus/1214345884958982144
    "角色·卡厄斯",
    "时装·放晴日",
    "改装件·猎犬奔袭-涂装",
    "滑翔翼·天际猎手",
    # 1.2 破晓前 https://www.bilibili.com/opus/1219571427779280904
    "角色·真红",
    "时装·地海高校生",
    "改装件·赤炎龙影-涂装",
    "滑翔翼·蔽日之影",
    # 1.2 生命线 https://www.bilibili.com/opus/1227333685680799761
    "角色·伊洛伊",
    "时装·大魔导师",
    "改装件·我们仨-涂装",
    "滑翔翼·小羊直升机",
    # 1.3 惑心谲影 https://www.bilibili.com/opus/1235172466950668312
    "角色·残虹",
    "时装·秋色闲章",
    "改装件·白沙幻境-涂装",
    "滑翔翼·赤练",
    # 1.3 全频带漫游中！ https://www.bilibili.com/opus/1242949793770111045
    "角色·灵可",
    "时装·星间漫游",
    "改装件·高速运转的灵可-涂装",
    "滑翔翼·超级恶灵！",
    # 未来卡池模板
    # "角色·____",
    # "时装·____",
    # "改装件·____-涂装",
    # "滑翔翼·____",
]

[pools."标准棋盘"]
# 标准棋盘也称「常驻」，几乎不会发生变动
items = [
    # S 级角色
    "角色·早雾",
    "角色·白藏",
    "角色·哈索尔",
    "角色·法帝娅",
    "角色·达芙蒂尔",
    "角色·九原",
    # A 级角色
    "角色·翳",
    "角色·薄荷",
    "角色·哈尼娅",
    "角色·埃德嘉",
    "角色·阿德勒",
    "角色·海月",
    # A 级弧盘
    "弧盘·被遗忘者",
    "弧盘·开始净空",
    "弧盘·当心头顶",
    "弧盘·勿忘伞",
    "弧盘·拔刀",
    # B 级弧盘
    "弧盘·成功的第一步",
    "弧盘·「电音」狂欢",
    "弧盘·笑口常开",
    "弧盘·危险游戏",
    "弧盘·「我们。」",
    # 道具
    "道具·捏造骰子", # 用于标准棋盘的抽卡道具
    "道具·失纬棋子",
    "道具·迷迭棋子",
]

[pools."弧盘研募"]
# 弧盘研募由几乎不会变动的常驻部分和需要随版本更新的限定部分组成
# 每个限定 S 角色有一个对应的 S 级弧盘（俗称「专武」）
items = [
    # 常驻 S 级
    "现实避难所",
    "漆黑青春妄想",
    "好狗狗走四方",
    "茶花会",
    "焰魂狂飙",
    # 常驻 A 级
    "被遗忘者",
    "开始净空",
    "当心头顶",
    "勿忘伞",
    "拔刀",
    # 常驻 B 级
    "成功的第一步",
    "「电音」狂欢",
    "笑口常开",
    "危险游戏",
    "「我们。」",
]

limited_s_items = [
    # 以下内容需要随版本更新
    # 1.0 猛虎特刊 https://www.bilibili.com/opus/1193985878093987859
    "预备备",
    # 1.0 名月特刊 https://www.bilibili.com/opus/1199165608673935377
    "行进于时间之外",
    # 1.1 夜曲特刊 https://www.bilibili.com/opus/1206606639476506624
    "「最后一朵玫瑰」",
    # 1.1 追猎特刊 https://www.bilibili.com/opus/1214376235343282176
    "众人追寻之物",
    # 1.2 决意特刊 https://www.bilibili.com/opus/1219579158672179201
    "穿过胭红蜃景",
    # 1.2 启门特刊 https://www.bilibili.com/opus/1227348782484553872
    "错误的门",
    # 1.3 摄心特刊 https://www.bilibili.com/opus/1235180197940035603
    "噬心诡刃",
    # 1.3 万籁特刊 https://www.bilibili.com/opus/1242980938674077703
    "远行者之声",
]
