[pools."限定棋盘"]
items = [
    "弧盘·当心头顶",
    "弧盘·「电音」狂欢",
    "弧盘·笑口常开",
    "弧盘·成功的第一步",
    "弧盘·危险游戏",
    "弧盘·「我们。」",
    "弧盘·开始净空",
    "弧盘·勿忘伞",
    "弧盘·拔刀",
    "弧盘·被遗忘者",
    "弧盘·现实避难所",
    "弧盘·穿过胭红蜃景",
    "道具·质实骰子",
    "道具·迷迭棋子",
    "道具·失纬棋子",
    "道具·捏造骰子",
    "角色·薄荷",
    "角色·哈尼娅",
    "角色·翳",
    "角色·娜娜莉",
    "角色·阿德勒",
    "角色·早雾",
    "角色·法帝娅",
    "角色·哈索尔",
    "角色·埃德嘉",
    "角色·达芙蒂尔",
    "角色·九原",
    "角色·海月",
    "角色·浔",
    "角色·安魂曲",
    "角色·真红",
    "滑翔翼·幽兰",
    "滑翔翼·好柿成双",
    "滑翔翼·蔽日之影",
    "改装件·番茄酱巡航-涂装",
    "改装件·赤炎龙影-涂装",
]

[pools."标准棋盘"]
items = [
    "弧盘·当心头顶",
    "弧盘·「电音」狂欢",
    "弧盘·笑口常开",
    "弧盘·成功的第一步",
    "弧盘·危险游戏",
    "弧盘·「我们。」",
    "弧盘·开始净空",
    "弧盘·勿忘伞",
    "弧盘·拔刀",
    "弧盘·被遗忘者",
    "弧盘·现实避难所",
    "弧盘·穿过胭红蜃景",
    "道具·质实骰子",
    "道具·迷迭棋子",
    "道具·失纬棋子",
    "道具·捏造骰子",
    "角色·薄荷",
    "角色·哈尼娅",
    "角色·翳",
    "角色·娜娜莉",
    "角色·阿德勒",
    "角色·早雾",
    "角色·法帝娅",
    "角色·哈索尔",
    "角色·埃德嘉",
    "角色·达芙蒂尔",
    "角色·九原",
    "角色·海月",
    "角色·白藏",
]

[pools."弧盘研募"]
items = [
    "当心头顶",
    "「电音」狂欢",
    "笑口常开",
    "成功的第一步",
    "危险游戏",
    "「我们。」",
    "行进于时间之外",
    "焰魂狂飙",
    "茶花会",
    "「最后一朵玫瑰」",
    "开始净空",
    "勿忘伞",
    "拔刀",
    "被遗忘者",
    "现实避难所",
    "穿过胭红蜃景",
]
